### ISSUE TITLE
No city selected

### ISSUE THREAD

**Issue by bitSheriff** [bitSheriff/norsevpn#2]
if no city is selected in the location tree the string "" needs to be entered not "none" so the nordvpn call is successful

**Comment by JawadHalabiMTB** [comment]
Hi @bitSheriff i've already fixed the issue and here is the commit ID: 14c8d51752c4bd447e88d7ac34264e8d73259796

I hope it fix the issue 

BR

**Comment by bitSheriff** [comment]
hi @JawadHalabiMTB 
thanks for the contribution, the nordvpn client does unfortunately not take "none" either. Try
```
cty =""
```

i think that should fix it
